.gitignore, README.md, jest.config.js, package.json, src/converters.ts, src/invocationValidator.ts, src/types/index.ts, tools/execute.ts, yarn.lock
Back ports some recent changes to the okta integration and updates to latest template. I have executed this on my laptop with success. Going to push this to NPM to make available for deployment.
=> Update to latest

package.json, src/converters.ts, src/types/index.ts
Array property not supported on the edge in Neptune - has to stringify
=> Fix array property not being stored correctly in Neptune

.travis.yml, package.json
Must merge to master because this was released to NPM.
=> Release 0.4.3

package.json, src/executionHandler.ts, src/index.ts, src/initializeContext.ts, src/invocationValidator.ts, src/types/index.ts, tools/execute.ts, yarn.lock
These changes will make this open source integration execute as a sequence of phases with parallel steps. The `IntegrationInvocationConfig` returned by the integration is used in the deployment project to generate a Step Functions state machine.
=> Introduce step execution

package.json, src/index.ts, src/okta/cache.ts, src/okta/fetchBatchOfUsers.ts, src/okta/types/client.ts, src/synchronizers/synchronizeUsers.ts, yarn.lock
Uses forthcoming changes provided by the integration SDK to allow iterating a step.
=> Iterate fetch and use cache

package.json, src/index.ts, src/okta/fetchBatchOfUsers.ts, yarn.lock
Trying to create smaller PRs. :)
=> Upgrade SDK to 28.1.2

src/okta/fetchBatchOfResources.ts, src/okta/fetchBatchOfUsers.ts, src/okta/types/applications.ts, src/okta/types/devices.ts, src/okta/types/groups.ts, src/okta/types/index.ts, src/okta/types/users.ts
Prepare the code for more easily iterating more resources (I.E. applications).
=> Extract resource iteration logic

src/okta/fetchBatchOfResources.ts
=> Remove specific resource references in iterator

docs/jupiterone-io/graph-okta.md
This will need to be published to https://support.jupiterone.io/hc/en-us/articles/360022902573-Okta.
=> Update Okta API token doc

src/okta/fetchBatchOfApplicationUsers.ts
This will cease iteration when there are no applications to fetch users for.
It will fail the step when the applications were not fetched in a previous step. This is a common pattern we want to move away from, which is aimed at protecting from deletes when we cannot fetch data. It's found in some of the smaller integrations (read: not AWS), where we want a complete set or nothing. The approach we're working toward will simply avoid any deletes when fetches are incomplete, but we'll need to instrument that process to notify us when there is a trend of never completing ingestion for an account/integration instance.
=> Terminate integration on incomplete fetch

src/okta/fetchBatchOfApplicationUsers.ts
=> Fix app users crash for after unauthorized apps

CHANGELOG.md, package.json, src/util/isValidOktaOrgUrl.test.ts, src/util/isValidOktaOrgUrl.ts
=> Fix okta domains

CHANGELOG.md, package.json, src/okta/fetchBatchOfApplicationUsers.ts, src/okta/fetchBatchOfApplications.ts, src/okta/fetchBatchOfResources.ts, src/okta/fetchBatchOfUsers.ts, src/synchronizers/synchronizeApplications.ts, src/synchronizers/synchronizeGroups.ts, src/synchronizers/synchronizeUsers.ts, src/util/logIfForbidden.ts, src/util/retryApiCall.ts
=> 103 api etimedout

CHANGELOG.md, package.json, src/okta/fetchBatchOfApplications.ts, src/okta/fetchBatchOfResources.ts, src/okta/fetchBatchOfUsers.ts
=> 111: Pass iterationState.state.after qParam to fetchBatchOfUsers

CHANGELOG.md, package.json, src/index.ts, src/okta/fetchBatchOfApplicationUsers.ts, src/okta/fetchBatchOfApplications.ts, src/okta/fetchBatchOfResources.ts, src/okta/fetchBatchOfUsers.ts, src/types/index.ts, src/util/extractCursorFromNextUri.ts, src/util/retryApiCall.ts
Bonus: add typing to `iterationState.state`
=> Stop retrying 404

.github/workflows/build.yml
This was already working but changing just to keep a consistent code style.
=> deprecate set-env

package.json, src/okta/fetchBatchOfApplicationUsers.ts, src/okta/fetchBatchOfUsers.ts, yarn.lock
I'd like to also bump this to 1.8.1 and deploy.
=> Downgrade okta client version

CHANGELOG.md, package.json, src/client.ts, yarn.lock
Hi @aiwilliams and @mknoedel !
Here are some further fixes for Okta, based on a Sentry 404 error that popped up today for a missing Okta group when we went to pull users from it.
--Kevin
=> Catching 404s for deleted objects, package updates

CHANGELOG.md, package.json, src/client.ts, yarn.lock
Hi @aiwilliams !
Here is my suggestion for INT-1273, OktaAPIError.
--Kevin
=> catch for 400 errors

CHANGELOG.md, src/converters/device.ts
Hi @aiwilliams !
While working on the 400 error issue, I discovered this unrelated bug.
--Kevin
=> Fix devices

src/client.ts, src/converters/device.ts
Hi @aiwilliams !
I still can't reproduce the error - I need an Okta account that doesn't have the Rules feature to try it against. I made a brand-new dev account for myself, but during the 30 day trial, the Rules feature is enabled, so this error doesn't throw.
That said, I'm trying another way to catch this specific error. See if this works better.
Also, fixed 2 unrelated bugs in this PR that I found while poking around. 
--Kevin
=> Fix rules400 error, part 2

.github/workflows/build.yml, docs/jupiterone.md, package.json, src/okta/createOktaClient.ts, yarn.lock
Added retry to fetch and updated J1 SDK package
=> Int 1276 improved error handling

docs/jupiterone.md
Adding information on what level of Administrator is required to access Okta values.
=> Adding Administrator Level Documentation Details

docs/jupiterone.md
Updating documentation to specify which permissions can/can't ingest role data.
=> Updating documentation around role data ingestion

CHANGELOG.md, package.json, src/converters/device.ts, src/okta/types/devices.ts, src/types/entities.ts
Added `lastVerified` and `authenticatorName` properties to the `mfa_device` entity.
=> IDEA-429 - Add properties to `mfa_device`

CHANGELOG.md, docs/jupiterone.md, package.json, src/client.ts, src/steps/constants.ts, src/steps/groups.ts, src/steps/index.test.ts
- Increase page size when fetching members of a group
- Separate group to user relationship logic into separate steps
**NOTE**: The recording tests need to be updated. These changes are experimental and I plan to release a beta version initially. Will update recording tests later.
=> INT-5828 - Attempt to improve integration performance

CHANGELOG.md, src/okta/createOktaClient.ts, src/steps/constants.ts, src/steps/groups.ts, src/steps/roles.ts, src/util/jobState.ts
- Remove Okta Node.js client caching
=> INT-5828 - Performance improvements

CHANGELOG.md, src/converters/user.ts, src/okta/types/users.ts
Added `hiredOn` and `terminatedOn` properties to `okta_user` entity.
=> INT-5892 - Add hiredOn and terminatedOn properties

CHANGELOG.md, package.json
Update version to 2.5.4
- New logic added to support multiple relationships for the same applications group.
=> Update version to v2.5.4

src/converters/device.ts, src/converters/devices.test.ts, src/okta/types/devices.ts
https://jupiterone.atlassian.net/browse/PTR-895 - ticket
=> Ptr 895 pull profile information from raw data to properties on okta mfa device

.github/workflows/integration-deployment.yml
Adding new Github Actions workflow to automatically deploy to j1 integration-deployments project
=> INT-7418 Adding integration deployment workflow

src/okta/createOktaClient.ts
=> Info the API rate limit for the API endpoints used

src/client.ts, src/steps/groups.ts
=> execute group->users relationship steps sequentially, remove timeout
